# Generated by Django 4.2.6 on 2023-10-31 13:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_assurance', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ID_client', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_client', models.CharField(max_length=100)),
                ('Prenom_client', models.CharField(max_length=100)),
                ('Age_Client', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Num_sec_social_client', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', message='Num_sec_social_client must be 13 digits.')])),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_commande', models.DateField()),
                ('Quantite_commande', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('ID_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_fournisseur', models.CharField(max_length=100)),
                ('Adresse_fournisseur', models.CharField(max_length=200)),
                ('Tel_fournisseur', models.IntegerField()),
                ('Mail_fournisseur', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('ID_medic', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_medic', models.CharField(max_length=100)),
                ('Lot_medic', models.CharField(max_length=20)),
                ('DCI', models.CharField(max_length=100)),
                ('Dosage_medic', models.IntegerField()),
                ('Prix_médic', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Prix_achat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Forme_medic', models.CharField(choices=[('Sirop', 'Sirop'), ('Comprimé', 'Comprimé'), ('Suppo', 'Suppo')], max_length=20)),
                ('Prémption_medic', models.DateField()),
                ('Quantite_medic', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_vente', models.DateField()),
                ('Quantite_vendue', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ID_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacieapp.client')),
                ('ID_medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacieapp.medicament')),
            ],
        ),
        migrations.AddConstraint(
            model_name='medicament',
            constraint=models.CheckConstraint(check=models.Q(('Dosage_medic__gt', 0)), name='positive_dosage'),
        ),
        migrations.AddConstraint(
            model_name='medicament',
            constraint=models.CheckConstraint(check=models.Q(('Prix_médic__gt', models.F('Prix_achat'))), name='selling_price_higher_than_purchase_price'),
        ),
        migrations.AddField(
            model_name='commande',
            name='ID_medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacieapp.medicament'),
        ),
        migrations.AddField(
            model_name='commande',
            name='Id_fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacieapp.fournisseur'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='ID_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacieapp.client'),
        ),
    ]
